#!/bin/sh

if [ -z $1 ]; then
    action="switch"
else
    action="$1"
fi

# Set correct directory, no matter where this is called from

# Ensure that we are in the script path
cd ${FLAKE_DIR}
# Set timestamp for automated commit message
timestamp=$(date +%s)
# Update current branch
git pull
# Update flake with latest software
nix-channel --update
nix flake update ${FLAKE_DIR}
# Add everything to the git tree
git add -A
# Commit updates
git commit -m "Updated the flake lock file @${timestamp}"
# Push changes
git push
# Switching to the new version
sudo nixos-rebuild ${action} --flake ${FLAKE_DIR}/#${hostname} --impure
