#!/bin/sh

# Set correct directory, no matter where this is called from
dir=$(dirname $0)
# Update the git repository before switching to the new version
source $dir/update
# Switching to the new version
sudo nixos-rebuild switch --flake ${dir}/#$hostname --impure

